### ISSUE TITLE
Setup Subscription Products 

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/FXProTools#1]
This would be achieved using "WooCommerce Subscription + WooCommerce"

Trial / Launch OTO:
+ $1.00 Trial (14 Days) for any package. (*Personal Volume - Distributor does not get the (PV) until the subscription has been active for 31 days.*)

Monthly Subscription Packages:
+ (Option 1) Customer "Signals" Package = $45 / Month + $55 Setup Fee 
(*Personal Volume - Customer "Signals" Package = 45 PV*)

+ (Option 2) Customer "Professional" Package  = $145 / Monthly + $200 Initial Setup Fee
(*Personal Volume - Customer "Professional" Package = 145 PV*)

+ (Option 3) Distributor "Business" Package = $160 / Monthly ($145 + $15 for "IBO Kit") + $200 Initial Setup Fee (*Personal Volume - Distributor "Business" Package = 145 PV*)

Upsell / Stand Alone Product
+ $25 / Monthly Renewal With AutoTrader (*Personal Volume - "AutoTrader" Package = 45 PV*)
+ $5000 / One Time "Coaching Package" (*Personal Volume - "AutoTrader" Package = 45 PV*)

Notes:
1. Certain Packages have a 14 day trial period, customer has to pay $1.00 (#35)

2. Users can permanently access their products for FREE by having 2 REFERRALS (3 for Business Package). The "Referral Only Counts" once referral has a fully active Subscription (Not Trial). (#13)
 
4. If customers REFERRALS goes down below the required #, they need to pay that month or refer someone 14 days before billing cycle. (#13)

5. Auto Trader can be purchased separately from Customer and Distributor packages.

6. Expired trial users will be redirected to Upgrade Access page (#28)

**Comment by sgerritse** [comment]
## Login condition if distributor or customer

Since we have 2 types of user(distributor, customer) each of them has restrictions since there are pages that can be only accessed by distributor or customer.

**Guest:** Can ONLY Access the "Funnel URLs + Checkout" from the "Marketing Links / Sale Funnels"

**Customer:** Can Access All Pages EXCEPT "Team Tab (http://fxprotools.com/team/)"

**Customer:** Can Access ALL Pages

**Comment by benedicksahagun** [comment]
I've applied the login access conditions

**Comment by sgerritse** [comment]
Do we have test users for this conditions @benedicksahagun ?

**Comment by benedicksahagun** [comment]
Customer:
testcustomer / testpassword

Business:
testdistributor / testpassword

You can use these test accounts @sgerritse

**Comment by benedicksahagun** [comment]
Here's the list of our products @sgerritse 
http://fxprotools.com/product/signals-trial
http://fxprotools.com/product/signals
http://fxprotools.com/product/professional
http://fxprotools.com/product/professional-trial
http://fxprotools.com/product/auto-trader
http://fxprotools.com/product/1-on-1-coaching
http://fxprotools.com/product/business
http://fxprotools.com/product/business-trial
