### ISSUE TITLE
Setup View Permissions Based on "Role"

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/FXProTools#11]
Guest (*Admin Option:* We need way to "tag" / or "categorize" the page / funnels templates. So that in the future when the admin adds more pages ("Capture, Landing, Webinar, Hangout") pages in the future, the system knows that "Guest" should be able to view these pages automatically.) 

+ http://fxprotools.com/marketing/funnels/ (Any Pages that get added in "Marketing Links / Funnels" all "Guest" should be allowed to see.)

<img width="1067" alt="screen shot 2017-09-08 at 2 22 30 am" src="https://user-images.githubusercontent.com/10511034/30198697-0607fe5c-943d-11e7-974f-b05c07aea53b.png">

<img width="1065" alt="screen shot 2017-09-08 at 2 22 40 am" src="https://user-images.githubusercontent.com/10511034/30198698-060a162e-943d-11e7-949e-1284d32a94d8.png">

..."Guests" should be able to go through the checkout process, so they should be able to see the cart & checkout pages.

Customers:
Refer to the "Customer Wireframe": 
https://drive.google.com/open?id=0B9QlVpKDdRNvWnhlSE4yb05oSUU

Distributor:
Refer to the "Distributors Wireframe":
https://drive.google.com/open?id=0B9QlVpKDdRNvYXE4YlJSNkxaYVE

Anything that is outside of these, should be be sent to the 404 Access Page:

![clean_404_landingpagestep 1](https://user-images.githubusercontent.com/10511034/30199429-adedbb5e-9440-11e7-9f05-d7586e909703.jpg)

...Or if they do not have the product, and need to upgrade their account they would see the "Upgrade" access page (Example for "Auto Trader" Upgrade):

![clean_access_landingpagestep 1](https://user-images.githubusercontent.com/10511034/30199401-95b8f062-9440-11e7-8dd2-ccaf4ab61ad8.jpg)

**Comment by jonelvinnaorbe** [comment]
@sgerritse done on 404 and upgrade

**Comment by benedicksahagun** [comment]
I've added categories for funnels as well @sgerritse

**Comment by sgerritse** [comment]
@jonelvinnaorbe or @benedicksahagun do we have different accounts to test this in? 

I am noticing the FXProTools main admin account is showing customer view (I'm pretty sure because I cant see marketing / funnels tab / pages)

**Comment by benedicksahagun** [comment]
You can use these account @sgerritse 

Customer:
testcustomer / testpassword

Business:
testdistributor / testpassword

There were some bugs I have to fixed, it should be fine now.

**Comment by benedicksahagun** [comment]
@sgerritse please review

**Comment by sgerritse** [comment]
@benedicksahagun I noticed that when you log into the accounts it is forwarding the user to /wc-account/ page instead of the correct dashboard based on package:

Customer:
testcustomer / testpassword

<img width="1318" alt="screen shot 2017-09-28 at 1 33 16 am" src="https://user-images.githubusercontent.com/10511034/30950791-165aaf6a-a3ed-11e7-85c8-2eb0f98148f2.png">

Business:
testdistributor / testpassword

<img width="1267" alt="screen shot 2017-09-28 at 1 34 31 am" src="https://user-images.githubusercontent.com/10511034/30950801-316accfe-a3ed-11e7-8baf-8769946c0701.png">

**Comment by benedicksahagun** [comment]
I've updated it @sgerritse

**Comment by sgerritse** [comment]
@benedicksahagun you fixed the WC-Account, which is great - but when the user signs in... it still is taking them to the my account page instead of the http://fxprotools.com/dashboard/

**Comment by benedicksahagun** [comment]
Oh, I've fixed it now @sgerritse
