### ISSUE TITLE
Access Your Products 

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/FXProTools#27]
When the customer visits this page here: 
http://fxprotools.com/access-products/

For the most part, this page is just display what products the customer has purchased (#1):
<img width="402" alt="screen shot 2017-09-08 at 11 35 48 am" src="https://user-images.githubusercontent.com/10511034/30219521-48787d78-948a-11e7-98df-e67ce6dc6a03.png">

This section below, is showing ALL the packages that are available. Showing both packages the have already purchased, and have not purchased yet... (#1) with one click "upgrade" or "access page" buttons:
<img width="1175" alt="screen shot 2017-09-08 at 11 40 22 am" src="https://user-images.githubusercontent.com/10511034/30219655-be8e2e0e-948a-11e7-9a7e-c909d8faed53.png">

**Comment by benedicksahagun** [comment]
I've integrated the info on the template except the remaining trial day data, will get it from Sumeena and finish this.

**Comment by benedicksahagun** [comment]
I've integrated this page fully now @sgerritse
