### ISSUE TITLE
Access Denied / Upgrade Page

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/FXProTools#28]
The Access Denied / Upgrade Pages should all look and function like this:

![clean_access_landingpagestep 1](https://user-images.githubusercontent.com/10511034/30220046-ff4fbb82-948b-11e7-86a0-0a724608f541.jpg)

PSD: https://drive.google.com/open?id=0B9QlVpKDdRNvQTY4UmVMaFFCbkk

![clean_access_landingpagestep 2](https://user-images.githubusercontent.com/10511034/30220178-7112e8a2-948c-11e7-9464-cc010fe1a05a.jpg)

+ The Upgrade Should Apply to The "Upsell" and "Stand Alone" Products" (#1), if the product is a "Webinar" product it should trigger popup as explained here (#19)

**Comment by jonelvinnaorbe** [comment]
@sgerritse ready for review. Thanks.
