### ISSUE TITLE
Webinar / Coaching Page

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/FXProTools#29]
Currently the "Webinar / Coaching" tab is displaying the single product page it should link to http://fxprotools.com/sessions/ page:
<img width="1222" alt="screen shot 2017-09-08 at 12 00 59 pm" src="https://user-images.githubusercontent.com/10511034/30220462-7d083c7e-948d-11e7-89d4-c3c93257e0a6.png">

...It should be showing the feed of sessions:
<img width="901" alt="screen shot 2017-09-08 at 12 01 26 pm" src="https://user-images.githubusercontent.com/10511034/30220500-9d091b42-948d-11e7-9880-b54972f2fbab.png">

...If Empty, you can put the words "No Sessions Scheduled" in the white space.

**Comment by sgerritse** [comment]
Please also make sure that the "Upsell" page looks like this (#28)

**Comment by jonelvinnaorbe** [comment]
@sgerritse ready for checking. Thanks.
