### ISSUE TITLE
"Customized" Checkout Page

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/FXProTools#30]
The checkout page **_should look exactly_** like this https://forcefactor.me/j/t/ but red theme: 

The following functions / triggers should happen on this page:
+ If the user attempts to leave the page, without finishing the checkout process. A "Exit Popup" should appear, just as it does on the sample site. (Once the user clicks "close", or leaves the offer should NOT APPEAR AGAIN for 12 hours for the cookie / cached guest.)

<img width="662" alt="screen shot 2017-09-08 at 12 09 27 pm" src="https://user-images.githubusercontent.com/10511034/30220806-ef0ba530-948e-11e7-96d1-1aeb749bc5b7.png">

.PSD Download Here: https://drive.google.com/open?id=0B9QlVpKDdRNvSXFPbzFJQzJCTms
.JPG Download Here: https://drive.google.com/open?id=0B9QlVpKDdRNvcWo5QXkzaHlxZlE

![exitpopup](https://user-images.githubusercontent.com/10511034/30222423-1de31e50-9495-11e7-8f0f-b9a373435898.jpg)

...More importantly, you want to make sure that we also re-create this script here (Note: these are not really live orders. They are just cycling through every order & fake orders to give the illusion that a sale has just been made at that moment:
<img width="349" alt="screen shot 2017-09-08 at 12 57 02 pm" src="https://user-images.githubusercontent.com/10511034/30222589-3d0928ba-9495-11e7-908e-4f34b8c56ec9.png">

I would just recommend once we have the member data imported, we can use our customer data and just rotate that script through our existing users. (Fake the time "8 minutes ago, 1 minutes ago, 3 seconds ago, 1 hour ago, etc..)

**Comment by jonelvinnaorbe** [comment]
@creativegeniusod added the frontend layout here http://fxprotools.com/checkout-custom/ Thanks

**Comment by benedicksahagun** [comment]
For checking @sgerritse

**Comment by sgerritse** [comment]
@benedicksahagun how would I test this? Can you provide the video of this being completed & tested. (http://useloom.com)

**Comment by benedicksahagun** [comment]
I've updated this @sgerritse 

Demos:
Trial - https://www.useloom.com/share/0b786356a85942c6ad4a9ce1d5f1291a
Regular - https://www.useloom.com/share/0f1b3114cc454cf1823457fae38cb13b
