### ISSUE TITLE
Courses / Lessons

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/FXProTools#31]
The first thing I noticed was that it does not hold the styling. It just makes it plain text.

<img width="751" alt="screen shot 2017-09-08 at 2 38 41 pm" src="https://user-images.githubusercontent.com/10511034/30226273-6ebc18dc-94a3-11e7-9939-5c4a8d90c471.png">

....Whereas if you look here in the visual layout, it shows styled like this (picture centered, line-spacing don't show - see screenshot below ):

<img width="861" alt="screen shot 2017-09-08 at 2 39 24 pm" src="https://user-images.githubusercontent.com/10511034/30226332-a070573a-94a3-11e7-879b-1f26a750f53a.png">

...The "Enable Video Progression" also known as "Video Embed for Lesson", doesn't work (It seems like the video is static)....

<img width="843" alt="screen shot 2017-09-08 at 2 47 18 pm" src="https://user-images.githubusercontent.com/10511034/30226656-d2c5153a-94a4-11e7-8c45-c9323dea4ee4.png">

...Lets make sure that all the other options with the lessons as well. LMS should be integrated fully.
<img width="888" alt="screen shot 2017-09-08 at 2 50 16 pm" src="https://user-images.githubusercontent.com/10511034/30226722-10116aba-94a5-11e7-89cf-8ac5bbd1b5dd.png">

...If you look here (http://fxprotools.com/lesson/creating-a-demo-account-for-trading/) you will see that the "course content" goes outside the box. (Also, I have placed an image here - this should be HTMLS / CSS table.)

<img width="665" alt="screen shot 2017-09-08 at 3 36 20 pm" src="https://user-images.githubusercontent.com/10511034/30228395-808f9784-94ab-11e7-84ff-364b46e28cb1.png">

.PSD Can Be Downloaded Here: https://drive.google.com/open?id=0B9QlVpKDdRNvUEU0M0NNbDVZUmc 

....The "Course Outline" Menu (Lesson inside course) on the left, should look like this:
<img width="300" alt="screen shot 2017-09-08 at 3 39 02 pm" src="https://user-images.githubusercontent.com/10511034/30228516-2742a7f6-94ac-11e7-804a-e90b57d06f3c.png">
 
Which is pulled from this site here: https://www.babypips.com/learn/forex

**Comment by benedicksahagun** [comment]
Hi @sgerritse it will be difficult to integrate all of the functions without a wireframe. I suggest we only pick features we will really use because integration  of LMS on custom theme is difficult and will take time.

**Comment by sgerritse** [comment]
@benedicksahagun I understand. Here are the functions which we will need:

**For Courses:** 
1. Course Materials (You can ignore for now)
2. Course Price Type (I think this works already - just test it & confirm)
3. Course Access List (I think this works already - based on woocommerce package.)
4. Sort Lesson By (I think this works already - just test it & confirm)
5. Sort Lesson Direction (I think this works already - just test it & confirm)
6. Enable Course Prerequisites (I think this works already - just test it & confirm)
7. Enable Course Points (You can ignore for now)
8. Disable Lesson Progression (I don't think this works - confirm & test?)
9. Expire Access (I don't think this works - confirm & test?)
10. Hide Course Content Table (You can ignore for now)
11. Associated Certificate (You can ignore for now)


**For Lessons:** 
1. Associated Course (I think this works already - just test it & confirm)
2. Forced Lesson Timer (I don't think this works - confirm & test?)
3. Upload Assignment (You can ignore for now)
4. Sample Lesson (You can ignore for now)
5. Make Lesson visible X Days After Sign-up (You can ignore for now)
6. Make Lesson Visible on Specific Date (You can ignore for now)
7. Enable Video Progression + Options)  (I don't think this works - confirm & test?)

**Comment by benedicksahagun** [comment]
For Courses:

Course Price Type
- Because of limitation on Woocommerce Subscription we always set this value to "Free". 
- Access restriction will depend on User Access Level, this is an optimal solution so we don't have to update every products when we add new course.
- Courses will be grouped "Course Category"
Course Access List
- This is dynamically populated, works as intended
Sort Lesson By 
- Applied and tested
Sort Lesson Direction
- Applied and tested
Enable Course Prerequisites
- Applied and Tested
Disable Lesson Progression
- Applied and Tested
Expire Access
- We manage access on product level so I believe this won't be a problem

For Lessons:

Associated Course
- Tested
Forced Lesson Timer 
- Work In Progress
Enable Video Progression
- Applied and Tested

**Comment by sgerritse** [comment]
@benedicksahagun great, the only thing I would suggestion on these:

**Course Price Type**

- Because of limitation on WooCommerce Subscription we always set this value to "Free".

- Access restriction will depend on User Access Level, this is an optimal solution so we don't have to update every products when we add new course.

- Courses will be grouped "Course Category" 


**Expire Access**

- We manage access on product level so I believe this won't be a problem
For Lessons.

## Can we hide these options from the theme options so we are not confusing client when we pass this off to them? (Considering updates conflicts etc.)

**Comment by benedicksahagun** [comment]
We can't hide these options, since we also have "advanced training" and we want to set the value of those courses to "Buy Now"

**Comment by sgerritse** [comment]
@benedicksahagun  When I click on "support & resistance" (1st course according to the screenshot):
<img width="927" alt="screen shot 2017-09-15 at 3 55 12 pm" src="https://user-images.githubusercontent.com/10511034/30500894-52d403d8-9a2e-11e7-8fc5-a2cc3e6a0f4d.png">

It give error "You must finish the previous lesson first". (Can we also make this error a "tool tip" message instead of redirecting them to a empty page?)

**Comment by benedicksahagun** [comment]
I've updated it @sgerritse please check.
https://www.useloom.com/share/82a1bcad084d4110b961046515aba928

**Comment by sgerritse** [comment]
Love it, Thanks @benedicksahagun. I will marked this closed.
