### ISSUE TITLE
Free Trial or Dollar Amount Trial

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/FXProTools#35]
Currently it seems that all the products (#1 / #33 ) only have one option for "Trial", either active for FREE ($0.00) or its not active and member has to pay full price. 

<img width="930" alt="screen shot 2017-09-09 at 6 23 21 pm" src="https://user-images.githubusercontent.com/10511034/30244460-19910428-958c-11e7-9fd3-5dbb78648d20.png">
 
We need to make sure we have the option to "Set our own" dollar amount, the trial should actually be $1.00 and not $0.00. (We might change the price in future to $0.97) or we may only charge a $0.01 so keep this in mind when coding the option.)

**Comment by creativegeniusod** [comment]
Now we have an option to set Trial Amount, which will got deducted as soon as the Transaction is made, further if a product has Signup fee along with the subscription fee, then it will got deducted once the Trial Period ends. So for first month of subscription the deducted amount will be Signup + Subscription
and for rest of the months, only subscription amount will got deduct.
and here is the video-url for the same
https://www.useloom.com/share/6b967b05c17e4780a5339626d71a7a0e

**Comment by sgerritse** [comment]
@creativegeniusod , did you check the subscription for upgrades? 

Example: Signals $45 package -> to Professional, or Business, or adding auto trader, and all possible conditions related to upgrade / downgrade.

**Comment by sgerritse** [comment]
@benedicksahagun @jonelvinnaorbe Can we confirm this? Make sure this is working / setup properly in the system not a plugin. 

As always can you provide the video of this being completed & tested. (http://useloom.com)
