### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/FXProTools#45]
I noticed when trying to login to website with admin "fxprotools", it asks me for @email.com ending. 

http://fxprotools.com/login/

Then when I add this @email ending it doesn't work, even though the password is valid. 

...I am redirected to the WP-Admin where I can than login to the "FxProTools" account using the same email as I have been using in beginning: 

Here is video showing the issue: 
https://www.useloom.com/share/e122663b05fb4a1485117a48f64d7012

**Comment by creativegeniusod** [comment]
@sgerritse this issue is fixed, you can now login by using your email address also.
here you can check: https://www.useloom.com/share/f4826c83244340918192639adc16c811
